name: Deploy Frontend

env:
  CONTAINER_REGISTRY: roelvandegrint.azurecr.io
  CONTAINER_IMAGE: cont-staffing-frontend:${{ github.sha }}
  RESOURCE_GROUP: rg-staffing-system

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [implement-employees-svc-index-call]
    paths:
      - '/frontend/**'
      - '.github/workflows/cont-staffing-frontend-deploy.yml'
      - '/azure/frontend*'

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: roelvandegrint.azurecr.io
          username: ${{ secrets.CONTSTAFFINGSYSTEMFRONTEND_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTSTAFFINGSYSTEMFRONTEND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_IMAGE }}
          file: ./frontend/Server/Dockerfile
          context: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTSTAFFINGSYSTEMFRONTEND_AZURE_CREDENTIALS }}

      - name: Deploy infra
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./azure/frontend.bicep
          parameters: >-
            ./azure/frontend.parameters.json
            container_image=${{ env.CONTAINER_REGISTRY }}/${{ env.CONTAINER_IMAGE }}            
            container_registry_uri=${{ env.CONTAINER_REGISTRY }}
            container_registry_username=${{ secrets.CONTSTAFFINGSYSTEMFRONTEND_REGISTRY_USERNAME }}
            container_registry_password=${{ secrets.CONTSTAFFINGSYSTEMFRONTEND_REGISTRY_PASSWORD }}
          failOnStdErr: false
