name: Trigger auto deployment for cont-staffing-system-frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [bug/frontend-workflow-trigger]
    paths:
      - "/frontend/**"
      - ".github/workflows/cont-staffing-system-frontend-deploy.yml"

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: roelvandegrint.azurecr.io
          username: ${{ secrets.CONTSTAFFINGSYSTEMFRONTEND_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTSTAFFINGSYSTEMFRONTEND_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: roelvandegrint.azurecr.io/cont-staffing-system-frontend:${{ github.sha }}
          file: ./frontend/Server/Dockerfile
          context: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.CONTSTAFFINGSYSTEMFRONTEND_AZURE_CREDENTIALS }}

      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n cont-staffing-system-frontend -g rg-staffing-system --server roelvandegrint.azurecr.io --username  ${{ secrets.CONTSTAFFINGSYSTEMFRONTEND_REGISTRY_USERNAME }} --password ${{ secrets.CONTSTAFFINGSYSTEMFRONTEND_REGISTRY_PASSWORD }}
            az containerapp update -n cont-staffing-system-frontend -g rg-staffing-system --image roelvandegrint.azurecr.io/cont-staffing-system-frontend:${{ github.sha }}
